# -*- coding: utf-8 -*-
"""lab1_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2ChCMlkkpPOfl5asPIp9mwHLQlCYFmX
"""

import pandas as pd
df = pd.read_csv('housing.csv')

#Zmienna df jest obiektem typu DataFrame w bibliotece pandas.
#DataFrame to dwuwymiarowa struktura danych, która przypomina tabelę. Zawiera dane w postaci wierszy i kolumn, gdzie:
#Wiersze reprezentują poszczególne rekordy danych,
#Kolumny reprezentują różne cechy (zmienne), które opisują te rekordy.

df.head()
df.info()

df['ocean_proximity'].value_counts()
df['ocean_proximity'].describe()

df.hist(bins=50, figsize=(20,15))
plt.savefig('obraz1.png')

df.plot(kind="scatter", x="longitude", y="latitude",
alpha=0.1, figsize=(7,4))
plt.savefig('obraz2.png')

import matplotlib.pyplot as plt
df.plot(kind="scatter", x="longitude", y="latitude",
alpha=0.4, figsize=(7,3), colorbar=True,
s=df["population"]/100, label="population",
c="median_house_value", cmap=plt.get_cmap("jet"))

plt.savefig('obraz3.png')

numeric_df = df.select_dtypes(include=["number"])
correlation = numeric_df.corr()["median_house_value"].sort_values(ascending=False)
correlation_df = correlation.reset_index().rename(columns={"index": "atrybut", "median_house_value": "wspolczynnik_korelacji"})
correlation_df.to_csv("korelacja.csv", index=False)

import seaborn as sns


sns.pairplot(df)
plt.savefig("pairplot.png")
plt.close()

import pickle

from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df,test_size=0.2,random_state=42)
len(train_set),len(test_set)



train_numeric = train_set.select_dtypes(include=[float, int])
test_numeric = test_set.select_dtypes(include=[float, int])

train_corr = train_numeric.corr()

test_corr = test_numeric.corr()


with open("train_set.pkl", "wb") as f:
    pickle.dump(train_set, f)

with open("test_set.pkl", "wb") as f:
    pickle.dump(test_set, f)

