# -*- coding: utf-8 -*-
"""lab2_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZVQEVCMzp4m9zVM6uXdEsIFXBj1_aDK
"""

import numpy as np
import pickle
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix


mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist.data, mnist.target

y = y.astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

binary_target_train = (y_train == 0)
binary_target_test = (y_test == 0)
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, binary_target_train)

train_acc = accuracy_score(binary_target_train, sgd_clf.predict(X_train))
test_acc = accuracy_score(binary_target_test, sgd_clf.predict(X_test))

with open("sgd_acc.pkl", "wb") as f:
    pickle.dump([train_acc, test_acc], f)

cross_val_acc = cross_val_score(sgd_clf, X_train, binary_target_train, cv=3, scoring="accuracy")

with open("sgd_cva.pkl", "wb") as f:
    pickle.dump(cross_val_acc, f)

sgd_clf.fit(X_train, y_train)
y_pred = sgd_clf.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred)

with open("sgd_cmx.pkl", "wb") as f:
    pickle.dump(conf_matrix, f)